# Copyright (c) 2019-2022 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 

title: "Data Safe Demo"
stackDescription: "Data Safe Demo"
schemaVersion: 1.1.0
version: "0.0.1"
locale: "en"

variableGroups:
  - title: "Basic Hidden"
    visible: false
    variables:
    - "compartment_ocid"
    - "tenancy_ocid"
    - "region"

  - title: "Optional Configuration"
    variables:
    - "autonomous_database_name"
    - "use_only_always_free_eligible_resources"
    - "show_advanced"

  - title: "Advanced Resource Options - ATP"
    variables:
    - "autonomous_database_is_free_tier"

  - title: "Extras Hidden"
    variables:
      - "user_ocid"
      - "fingerprint"
      - "private_key_path"
      - "autonomous_database_db_version"
      - "autonomous_database_db_workload"
      - "autonomous_database_license_model"
      - "autonomous_database_visibility"
      - "autonomous_database_freeform_tags"
      - "autonomous_database_wallet_generate_type"
    visible: false

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Compartment"
    description: "The compartment in which to create ATP."

  region:
    type: oci:identity:region:name
    title: "Region"
    description: "The region for resources deployment."
    required: true

  user_ocid:
    type: oci:identity:user:id
    required: false
    title: "User"

  tenancy_ocid:
    type: oci:identity:tenancy:id
    required: true
    title: "Tenancy"

  autonomous_database_name:
    type: string
    title: "Database Name"
    description: "The name for the Autonomous Database instance. "
    minLength: 1
    maxLength: 10
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"
    required: true

  show_advanced:
    type: boolean
    default: false
    title: "Show advanced options?"
    description: "Shows advanced options"
    visible: true

  use_only_always_free_eligible_resources:
    type: boolean
    title: "Use only always free eligible resources?"
    description: "*** Unchecking this may use options that are not included or supported by Always Free eligible resources."
    visible: true

  autonomous_database_is_free_tier:
    type: boolean
    title: "Use always free Autonomous Database?"
    description: "Uses Always Free Transaction Processing Autonomous Database. Unchecking this option will provision a regular 1 OCPU ATP instance with License."
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - use_only_always_free_eligible_resources

  autonomous_database_visibility:
    type: enum
    enum:
    - "Public"
    # - "Private"
    title: "Choose autonomous database visibility type"
    description: "NOTE: Currently private endpoints are only supported if use local terraform. | If Private, creates the ADB with private endpoint. The autonomous database visibility will define if assign the ATP to a private subnet or allow secure access from everywhere."
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - use_only_always_free_eligible_resources

  autonomous_database_db_version:
    type: string
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - use_only_always_free_eligible_resources
  autonomous_database_license_model:
    type: string
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - use_only_always_free_eligible_resources
  autonomous_database_cpu_core_count:
    type: string
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - use_only_always_free_eligible_resources
  autonomous_database_data_storage_size_in_tbs:
    type: string
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - use_only_always_free_eligible_resources
  autonomous_database_wallet_generate_type:
    type: string
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - use_only_always_free_eligible_resources
  autonomous_database_db_workload:
    type: string
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - use_only_always_free_eligible_resources
  autonomous_database_freeform_tags:
    type: map
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - use_only_always_free_eligible_resources

outputGroups:
  - title: Passwords 
    outputs:
      - autonomous_database_password

outputs:
  autonomous_database_password:
    type: string
    title: "Database Admin Password"
    displayText: "Autonomous Database Admin Password"
    visible: false
  

